# app/config/security.yml
security:
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    firewalls:
        secured_area:
            pattern:    ^/
            anonymous: ~
            form_login:
                login_path:  login
                check_path:  login_check
            logout:
                path:   logout
                target: main_homepage

    access_control:
        - { path: ^/account, roles: ROLE_USER }

    providers:
         main:
             entity: { class: MainBundle\Entity\User, property: username }
    encoders:
            MainBundle\Entity\User:
                algorithm:        sha1
                encode_as_base64: false
                iterations:       1t