main_homepage:
    path:     /
    defaults: { _controller: MainBundle:Default:index }

account_register:
    path:     /register
    defaults: { _controller: MainBundle:Account:register }

account_create:
    path:     /register/create
    defaults: { _controller: MainBundle:Account:create }

login:
    pattern:   /login
    defaults:  { _controller: MainBundle:Secured:login }

login_check:
    pattern:   /login_check

logout:
    path:   /logout

account:
    pattern:  /account
    defaults: { _controller: MainBundle:Default:account }

account_draw:
    pattern:  /account/draw
    defaults: { _controller: MainBundle:Default:draw }