main_homepage:
    path:     /
    defaults: { _controller: MainBundle:Default:index }

account_register:
    path:     /register
    defaults: { _controller: MainBundle:Account:register }

account_create:
    path:     /register/create
    defaults: { _controller: MainBundle:Account:create }
    
account_password_reset_request:
    path:     /register/reset
    defaults: { _controller: MainBundle:Account:resetPasswordRequest }    

account_password_reset_request_form:
    path:     /register/reset_form
    defaults: { _controller: MainBundle:Account:resetPasswordRequestForm }   

public_space:
    path:     /public_space
    defaults: { _controller: MainBundle:Default:publicSpace}

account_password_reset:
    path:     /register/reset_password
    defaults: { _controller: MainBundle:Account:resetPassword }   

account_password_change_form:
    path:     /register/change_password_form
    defaults: { _controller: MainBundle:Account:changePasswordForm }   

account_password_change:
    path:     /register/change_password
    defaults: { _controller: MainBundle:Account:changePassword }   


account_confirm:
    path:     /register/confirm
    defaults: { _controller: MainBundle:Account:confirm }

login:
    pattern:   /login
    defaults:  { _controller: MainBundle:Secured:login }
#    schemes:  [https]
login_check:
    pattern:   /login_check
#    schemes:  [https]
logout:
    path:   /logout
#    schemes:  [https]
account:
    pattern:  /account
    defaults: { _controller: MainBundle:Default:account }
#    schemes:  [https]
account_draw:
    pattern:  /account/draw
    defaults: { _controller: MainBundle:Default:draw }  
#    schemes:  [https]
    
account_image_list:
    pattern:  /account/image_list
    defaults: { _controller: MainBundle:Default:imageList }  
#    schemes:  [https]    

account_image_save:
  pattern:  /draw/save
  defaults: { _controller: MainBundle:Default:saveImage }
#  schemes:  [https]

public_space_comment:
  pattern:  /public_space/comment
  defaults: { _controller: MainBundle:Default:comment }
#  schemes:  [https]

public_space_comments:
  pattern:  /public_space/comments
  defaults: { _controller: MainBundle:Default:comments }
#  schemes:  [https]