main_homepage:
    path:     /
    defaults: { _controller: MainBundle:Default:index }

account_register:
    path:     /register
    defaults: { _controller: MainBundle:Account:register }

account_create:
    path:     /register/create
    defaults: { _controller: MainBundle:Account:create }
    
account_password_reset_request:
    path:     /register/reset
    defaults: { _controller: MainBundle:Account:resetPasswordRequest }    

account_password_reset_request_form:
    path:     /register/reset_form
    defaults: { _controller: MainBundle:Account:resetPasswordRequestForm }   

account_password_reset:
    path:     /register/reset_password
    defaults: { _controller: MainBundle:Account:resetPassword }   

account_confirm:
    path:     /register/confirm
    defaults: { _controller: MainBundle:Account:confirm }

login:
    pattern:   /login
    defaults:  { _controller: MainBundle:Secured:login }
    schemes:  [https]
login_check:
    pattern:   /login_check
    schemes:  [https]
logout:
    path:   /logout
    schemes:  [https]
account:
    pattern:  /account
    defaults: { _controller: MainBundle:Default:account }
    schemes:  [https]
account_draw:
    pattern:  /account/draw
    defaults: { _controller: MainBundle:Default:draw }  
    schemes:  [https]
    
account_image_list:
    pattern:  /account/image_list
    defaults: { _controller: MainBundle:Default:imageList }  
    schemes:  [https]    

account_image_save:
  pattern:  /draw/save
  defaults: { _controller: MainBundle:Default:saveImage }
  schemes:  [https]